build:
  maxIssues: 0
  weights:
    complexity: 2
    LongParameterList: 1
    style: 1

processors:
  active: true
  exclude:
    - 'FunctionCountProcessor'

console-reports:
  active: true

output-reports:
  active: true

comments:
  CommentOverPrivateFunction:
    active: false

complexity:
  LongParameterList:
    active: false
  LongMethod:
    active: true
    threshold: 60
    ignoreAnnotated:
      - "Composable"
  TooManyFunctions:
    active: true
    thresholdInFiles: 15
    ignorePrivate: true
    ignoreAnnotated:
      - "Composable"
  LargeClass:
    active: true
    threshold: 600

style:
  UnusedPrivateMember:
    active: true
    ignoreAnnotated:
      - "Preview"
  MagicNumber:
    active: false
    ignoreNumbers: ["-1", "0", "1", "2"]
    ignoreAnnotated:
      - "Preview"
  MaxLineLength:
    active: true
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: true

naming:
  FunctionNaming:
    active: true
    functionPattern: '^[a-z][a-zA-Z0-9]*$'
    ignoreAnnotated:
      - "Composable"

performance:
  SpreadOperator:
    active: true

potential-bugs:
  UnreachableCode:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: false

formatting:
  active: true
  android: true
  autoCorrect: true
